---
- hosts: localhost 
  connection: local
  pre_tasks:
 

  - name: test
    bigip_device_group:
      name: "foo-group"
      password: "secret"
      server: "lb.mydomain.com"
      state: "present"
      user: "admin"
    delegate_to: localhost  
... 
